### ISSUE TITLE
Building KO containers for linux/riscv64 does not work

### ISSUE THREAD

**Issue by pascal71** [ko-build/ko#1129]
While trying to build KO containers for the RISCV64 architecture KO throws an error:

ko publish . --platform=linux/riscv64 --bare --tags "${tag}"
2023/09/10 09:48:46 Using base cgr.dev/chainguard/static:latest@sha256:a432665213f109d5e48111316030eecc5191654cf02a5b66ac6c5d6b310a5511 for containers
Error: failed to publish images: error building "ko://containers": no matching platforms in base image index

I believe this worked in the past.

Kind regards,

   Pascal van Dam

**Comment by imjasonh** [comment]
This is my fault. We recently stopped building the riscv64 variant of the default base image (`cgr.dev/chainguard/static:latest`) since it was a source of noise for us as Alpine's riscv64 packages were regularly out of sync from the other architectures, and we didn't think it was widely used.

The change in question was https://github.com/chainguard-images/images/pull/1194 if you're curious.

If you need riscv64 support you can [configure the base image](https://ko.build/configuration/#overriding-base-images) to use `alpine` instead, which has riscv64 support, or use another image with support for that platform.
