### ISSUE TITLE
Guidance on adding private CA certificates?

### ISSUE THREAD

**Issue by ari-becker** [ko-build/ko#1221]
Corporate users may require a private CA certificate to be installed in the final container. `ko` doesn't have some kind of native approach to passing in a private CA certificate as a parameter.

I believe the correct approach here is to use a base image which has the private CA certificate baked-in, but then there's a bootstrapping issue requiring another method (e.g. with a Dockerfile) to build the new base image with the private CA certificate.

I'd appreciate guidance / documentation on strategies to approach this; if I need to use a Dockerfile to bundle in the private CA certificate then I'm not sure what additional value `ko` is bringing to this use-case.

**Comment by imjasonh** [comment]
My recommendation would be to either bake the certs into the base image as you suggest, or possibly use a tool like https://github.com/dlorenc/incert to append a layer before or after ko to add the corp certs.

Hope this helps

**Comment by imjasonh** [comment]
Even if the base image is built with a dockerfile, IMO ko still adds value since each app on top of it doesn't need to use docker to build, and can be faster and more secure as a result. 

One team can periodically build the base with custom certs once, and dozens of app teams can independently build on that base without having to care about certs or docker.

**Comment by ari-becker** [comment]
Nice, I wasn't aware of `incert`.

I guess we can close this, unless someone wants to add this to the docs website.
