### ISSUE TITLE
Can we combine ko.local and --bare ?

### ISSUE THREAD

**Issue by eddycharly** [ko-build/ko#807]
Is this possible to combine `ko.local` with `--bare` options to produce an image in the form `ko.local/something` ?
It looks like setting `KO_DOCKER_REPO=ko.local/something` produces an image with the name `ko.local`.

**Comment by imjasonh** [comment]
v0.12 fixed a bug with KO_DOCKER_REPO=ko.local/foo which might be what you're describing.

That should work and if not it's a bug we should fix

**Comment by eddycharly** [comment]
Looks like it’s a bug, I’m using `0.12`.

**Comment by imjasonh** [comment]
I've confirmed this behavior, and I believe it's a bug:

```
$ ko version
0.12.0
$ KO_DOCKER_REPO=ko.local/test ko build --bare
...
ko.local:b892c8419de3e2b9729a50707a75ba8643fe56c704bfe5625dcc7c19f1741c5f
```

This should be `ko.local/test:b89...`

**Comment by eddycharly** [comment]
Thanks for confirming the bug @imjasonh

**Comment by eddycharly** [comment]
@imjasonh can this come from this https://github.com/ko-build/ko/blob/516cae16672bfb6d527648ce309d1dfe772ae141/pkg/commands/options/publish.go#L37 never being assigned ?

**Comment by imjasonh** [comment]
`LocalDomain` is used by clients that use `ko` as a library (e.g., Skaffold), so it's not set by `ko` itself, and defaults to `ko.local`.

Support for `KO_DOCKER_REPO=ko.local/foo` is actually very new, prior to https://github.com/ko-build/ko/pull/796 we didn't support it at all -- only `KO_DOCKER_REPO=ko.local` exactly.

There seem to be a few lingering places where code assumes local images will be pushed to _exactly_ `ko.local`:

https://github.com/ko-build/ko/blob/9a1eae8517b457b23f14109437fa8201eda72c06/pkg/commands/config.go#L62
(for local base images, unrelated to this issue)

It looks like the issue is here:

https://github.com/ko-build/ko/blob/9a1eae8517b457b23f14109437fa8201eda72c06/pkg/publish/daemon.go#L72

`NewDaemon` is called when `strings.HasPrefix(KO_DOCKER_REPO, LocalDomain)`, here:

https://github.com/ko-build/ko/blob/9a1eae8517b457b23f14109437fa8201eda72c06/pkg/commands/resolver.go#L175

...but then `NewDaemon` just sets `LocalDomain` only, without any local repo component.

I've got a fix I'll send out shortly.

**Comment by eddycharly** [comment]
Thanks for looking at it @imjasonh !
This line looked suspicious https://github.com/ko-build/ko/blob/9a1eae8517b457b23f14109437fa8201eda72c06/pkg/commands/resolver.go#L177 and made me suspect `LocalDomain` was guilty.
