### ISSUE TITLE
symlinks are not followed on MacOS

### ISSUE THREAD

**Issue by mbrancato** [ko-build/ko#808]
The docs show that symlinks are followed when including `kodata` files. Since the `kodata` directory name is [hard-coded](https://github.com/google/ko/blob/cbe2784e523e536f4c17910ceff705801b54814d/pkg/build/gobuild.go#L510), symlinks are the only way to support static files / assets in other locations.

However, symlinks do not seem to be properly supported on MacOS where `./kodata` is a directory.

```shell
% touch blah
% ln -s ./blah ./cmd/foo/kodata
% ko build ./cmd/foo --push=false                                     
2022/08/31 07:55:09 Using base gcr.io/distroless/static:nonroot@sha256:1f580b0a1922c3e54ae15b0758b5747b260bd99d39d40c2edb3e7f6e2452298b for foo/cmd/foo
2022/08/31 07:55:09 Using build config foo for foo/cmd/foo
2022/08/31 07:55:09 Building foo/cmd/foo for linux/amd64
Error: failed to publish images: error building "ko://foo/cmd/foo": filepath.EvalSymlinks("/Users/mike/Documents/Code/foo/cmd/foo/kodata/blah"): EvalSymlinks: too many links
2022/08/31 07:55:11 error during command execution:failed to publish images: error building "ko://foo/cmd/foo": filepath.EvalSymlinks("/Users/mike/Documents/Code/foo/cmd/foo/kodata/blah"): EvalSymlinks: too many links
```

And if the linked item is a sub-directory instead, the result is a different error...

```shell
% ln -s ./assets/blah ./cmd/foo/kodata/
% ko build ./cmd/foo --push=false   
2022/08/31 08:00:44 Using base gcr.io/distroless/static:nonroot@sha256:1f580b0a1922c3e54ae15b0758b5747b260bd99d39d40c2edb3e7f6e2452298b for foo/cmd/foo
2022/08/31 08:00:44 Using build config foo for foo/cmd/foo
2022/08/31 08:00:44 Building foo/cmd/foo for linux/amd64
Error: failed to publish images: error building "ko://foo/cmd/foo": filepath.EvalSymlinks("/Users/mike/Documents/Code/foo/cmd/foo/kodata/blah"): lstat /Users/mike/Documents/Code/foo/cmd/foo/kodata/assets: no such file or directory
2022/08/31 08:00:45 error during command execution:failed to publish images: error building "ko://foo/cmd/foo": filepath.EvalSymlinks("/Users/mike/Documents/Code/foo/cmd/foo/kodata/blah"): lstat /Users/mike/Documents/Code/foo/cmd/foo/kodata/assets: no such file or directory
```

As an aside, it seems like it would be a good opportunity for `KO_DATA_PATH`  (or an option / setting in `.ko.yaml`) to be used at build to identify the location of static assets instead of relying only on a hard-coded path.

**Comment by imjasonh** [comment]
I think the issue is the `ln -s ./assets/blah/ ./cmd/foo/kodata` doesn't put `assets` into `kodata`, only `blah`.

Running this from the root of this repo on macOS.

```
$ mkdir -p ./assets/blah
$ touch ./assets/blah/foo.js
$ ln -s ./assets/blah ./test/kodata
$ ls ./test/kodata
a    b    kenobi    blah
```

So the error message is correct, there is no `./cmd/foo/kodata/assets` to be found.

Re: `KO_DATA_PATH`, I think I'd be willing to consider such a change. It might get confusing having different semantics for an env var named `KO_DATA_PATH` at run-time (today, where files you put in `kodata` at build-time are available) and build-time (per your proposal, overriding where to look for `kodata`) but I think that could be discussed in a PR that adds it. Nothing a little documentation and examples couldn't fix 😄
