### ISSUE TITLE
[maybe][bug] ko build always check `docker-credential-gcloud` and failed if not exists

### ISSUE THREAD

**Issue by FFengIll** [ko-build/ko#859]
If i run `ko build` with `.ko.yaml` and `export KO_DOCKER_REPO=ko.local`, then failed (as bellow).

> only set `defaultBaseImage: gcr.io/distroless/static-debian10:nonroot` in the .ko.yaml

I doubt whether it is a feature or bug?

> furthermore, env: MacOS, golang 1.18

---
Error: failed to publish images: error building "ko://xxx": error getting credentials - err: exec: "docker-credential-gcloud": executable file not found in $PATH, out: ``
2022/10/22 11:20:50 error during command execution:failed to publish images: error building "ko://xxx": error getting credentials - err: exec: "docker-credential-gcloud": executable file not found in $PATH, out: ``

**Comment by FFengIll** [comment]
I test it with same config in another linux (k8s pod with centos), everything works well.
Is it only error in macOS?

**Comment by imjasonh** [comment]
What might be happening is that you have a cred helper configured for `gcr.io`. Look for something in your `~/.docker/config.json` that looks like:

```
  "credHelpers": {
    "gcr.io": "gcloud",
  },
```

Having that configured tells `ko` (and `docker` and other tools) to call an executable called `docker-credential-gcloud` to try to get credentials for `gcr.io`. If that executable can't be found, these tools will fail.

`ko` makes a request to gcr.io to fetch the base image, which you've configured to be `gcr.io/distroless/static-debian10:nonroot` -- the cred helper is invoked even though the image is publicly accessible.

What works on your centos machine is (probably) that the cred helper isn't configured, so you're not bothering to call `docker-credential-gcloud` which doesn't exist, and you fall back to make an anonymous request. This succeeds because the image is public.

**Comment by FFengIll** [comment]
@imjasonh  you are right.
I believe I have solved this problem by editing `~/.docker/config.json`.
Thx a lot~
