### ISSUE TITLE
Discussion: Can ko generate SLSA provenance?

### ISSUE THREAD

**Issue by developer-guy** [ko-build/ko#896]
Recently, Docker BuildKit announced that [SLSA provenance](https://slsa.dev/provenance/v0.2) would start being supported in the newer version [v0.11.0-rc1](https://github.com/moby/buildkit/releases/tag/v0.11.0-rc1) of BuildKit, which is nice because this kind of generations should be as closer as possible to the time that artifact was built.

> Provenance attestations basically describe how a build was produced and what sources/parameters were used.

- We can grab the git information through the source code where ko executes, which is the answer of the _**what sources were used**_ ✅
- Ko uses some Go build arguments under the hood while building the binary, which is the answer of the _**how a build was produced and what parameters were used**_ ✅
- Ko can know the time the build happened, so it can provide other types of metadata information about the build to fill the _metadata_ object of the provenance ✅

So, we (w/@dentrax) thought it'd be great if ko could generate SLSA provenance because it has everything it needs to create that file.

WDYT @imjasonh?

**Comment by imjasonh** [comment]
Git information and build args should already be exposed through `go version -m`, we'd just need to pass them into whatever slsa format is appropriate.

Are there any docs about how buildkit attaches the information? Do they just put it in the config somewhere, or is it a separate artifact? Is it signed somehow?

**Comment by Dentrax** [comment]
We're really looking forward to seeing this support in `ko`! Could you please give us some guidance and a nudge in the right direction to get into this one? Thanks!

**Comment by imjasonh** [comment]
This, like most things, is blocked on signing support in `ko`, since cosign doesn't support unsigned attestations, like buildkit's embedded attestations.

If you want to make progress on this you can take a look at how we generate SBOMs, and make a parallel implementation that generates SLSA provenance attestations. You could have `ko` write the JSON documents to a file instead of attaching them to the image for now (I don't think we'd merge a PR like this, but it's progress at least).

This would help motivate signing in `ko` even more than it already is, since we'd see immediate obvious benefit from adding signing, in the form of signed SLSA attestations.

What are you using these attestations for today, and what do you expect to find in the documents? `ko`'s SLSA provenance document would probably say:

> `ko @ version` used `go @ version` to build the binary with `[these flags]`, from `[this Git commit] (dirty yes/no)`, to produce a binary with [this digest]"

...since that's all it really does. That's definitely _helpful_, but a lot of that information is already in the SBOM, or could be fairly easily. Is it the SLSA provenance format you're interested in specifically?

**Comment by Dentrax** [comment]
We (@developer-guy) took at the builder source code a bit and have some questions:

* Should we generate _n_ provenances _per_ architecture?
* Since `builder` is a function that takes some args, we're planning to pass `in_toto.Provenance` object in `context` such as `context.WithValue(ctx, "provenance", g.slsaProvenance)` does it make sense?
* What about creating a new package under `/internal/provenance` vs put the provenance object(s) in `gobuild` struct (/w mutex if we thinking to produce multiple provenances)
* Do you have any other suggestions to eliminate known unknowns?

We will get into implementation according to your reviews.

**Comment by imjasonh** [comment]
> - Should we generate/produce n provenances per architecture?

Good question. I'd say the question of "what operation(s) were performed to produce this artifact" is probably best answered by "these N `go build` invocations that `ko` invoked" -- that sort of sounds like N provenances, each attached to the arch-specific artifact. I don't feel strongly though, and would consider any differing opinions here.

> * Since builder is a function that takes some args, we're planning to pass in_toto.Provenance object in context such as context.WithValue(ctx, "provenance", g.slsaProvenance) does it make sense?

This sounds like something we should consider at code review time. It's hard to tell without looking at the code if this is a simplification or if it would obfuscate things.

> * What about creating a new package under /internal/provenance vs put the provenance object(s) in gobuild struct (/w mutex if we thinking to produce multiple provenances)

In general, `internal` packages are great and we should use them more. Thank you for biasing in this direction. It may be hard to say for sure without seeing all the code together though.

---

I'd like to reiterate this question, since the answers might help us scope the solution more toward what you need:

> What are you using these attestations for today, and what do you expect to find in the documents? `ko`'s SLSA provenance document would probably say:
> 
> > `ko @ version` used `go @ version` to build the binary with `[these flags]`, from `[this Git commit] (dirty yes/no)`, to produce a binary with [this digest]"
> 
> ...since that's all it really does. That's definitely _helpful_, but a lot of that information is already in the SBOM, or could be fairly easily. Is it the SLSA provenance format you're interested in specifically?

**Comment by imjasonh** [comment]
Example of stuff available to us in the output of `go version -m <binary>` that we don't currently store in the SBOM, that could make sense in an attestation:

```
...
	build	-buildmode=exe
	build	-compiler=gc
	build	CGO_ENABLED=1
	build	CGO_CFLAGS=
	build	CGO_CPPFLAGS=
	build	CGO_CXXFLAGS=
	build	CGO_LDFLAGS=
	build	GOARCH=arm64
	build	GOOS=darwin
	build	vcs=git
	build	vcs.revision=7ce947817e2f59942cb181aa833bfd13533bcc19
	build	vcs.time=2023-03-07T19:35:10Z
	build	vcs.modified=false
```

**Comment by imjasonh** [comment]
Some notes from our discussion:
- `go version -m` includes env vars that Go deems interesting
- there may be other env vars that `ko` deems interesting (`KO_GO_BIN`, for example)
- we probably _shouldn't_ track `KO_DOCKER_REPO` since that's location-dependent, and not content-dependent
- we definitely _shouldn't_ track _all_ env vars, since they might be sensitive, especially in CI environments
- ideally we'd be able to write a test that reproduces an image based on the output of a previous image's SBOM+provenance (if the SBOM+provenance were generated by the same version of `ko` that is trying to reproduce)
