### ISSUE TITLE
SBOM score

### ISSUE THREAD

**Issue by RealHarshThakur** [ko-build/ko#956]
I used this CLI which gives out a SBOM score: https://github.com/eBay/sbom-scorecard
I compared the SBOM generated with ko with a SBOM generated from [syft](https://github.com/anchore/syft).   I was quite surprised for a scanner had more information than the build tool itself.  Since it's going to be simpler to download the SBOM and make decisions based on OCI artifact alone after build completion, I think having license information and increasing the score would be a step forward for ko.  Even having license information would be a huge improvement. Is this an upstream issue for Go tooling to not provide license information that ko could use?

ko SBOM:
```
4 total packages
0 total files
0% have licenses.
50% have package digest.
50% have package versions.
100% have purls.
0% have CPEs.
0% have file digest.
Spec valid? true
Has creation info? false
==
Spec Compliance: 25/25
Package ID: 10/20 (100% have purls and 0% have CPEs)
Package Versions: 10/20
Package Licenses: 0/20
Creation Info: 3/15 (The tool used to create the sbom does not have a version)
Total points: 48/100 or 48%
```  

Syft SBOM:
```
7 total packages
749 total files
57% have licenses.
14% have package digest.
100% have package versions.
100% have purls.
100% have CPEs.
100% have file digest.
Spec valid? true
Has creation info? true
==
Spec Compliance: 25/25
Package ID: 20/20 (100% have purls and 100% have CPEs)
Package Versions: 20/20
Package Licenses: 11/20
Creation Info: 15/15
Total points: 91/100 or 91%
```

**Comment by imjasonh** [comment]
`ko` only generates SBOMs for the contents it puts into the image -- that is, the Go binary and the Go modules it depends on. Information about the contents of the base image are expected to come from the base image, which can be identified by the image's base image annotations. SBOM-score doesn't seem to trace through these annotations to find base image information.

```
$ crane manifest $(ko build -P --platform=all) | jq
...
  "annotations": {
    "org.opencontainers.image.base.digest": "sha256:5ba1fe7f2fbf7467bcfe0caea261502ee7ffb503b6524481128b22584f2131c0",
    "org.opencontainers.image.base.name": "distroless.dev/static:latest"
  }
```

`ko` doesn't include license information about dependent Go modules at this time, because this information is not readily available -- there's no way, given a Go module, to know what it's license is. There are fairly reliable ways to guess, but we just haven't done that yet. Syft might be employing some of those ways to guess. #766 

`ko` could probably include file digests pretty easily, but I'm not sure what value it brings. Not saying it's not worth doing, I just don't understand how it would be used.

`ko` should include information about the `ko` version used to generate the SBOM. That's easy enough to add, and useful.

Also worth noting: Syft doesn't generate an SBOM for all platforms of a multi-platform image by default. It pulls the single platform image for the platform you're running on (effectively `docker pull`) then scans that image to generate the SBOM. This means that you'll get different results for this command when running on an amd64 machine vs an arm64 one:

```
$ syft gcr.io/jason-chainguard-public/github.com/imjasonh/sbom-fun@sha256:b2b847e47be21c047d8e9576dc779f38b6b2428a138a6c14e13187b735155f81
```

On an M1 Mac that includes `github.com/google/go-github/v45` -- on an x86_64 machine it will report `go-containerregistry` as a dep instead. And you'll need a `riscv64` machine to get Syft to generate an SBOM for that platform, and so on.

Ultimately there's a lot of nuance and difficulty involved in producing the best possible SBOMs. `ko` does some things well, and lacks in other areas. Having a tool to boil that down to a comparable score is useful, but naturally doesn't show the whole picture.

I'll keep this open since you've reported some useful low-hanging fruit we can achieve fairly easily, like file digests.

**Comment by RealHarshThakur** [comment]
Thanks for looking into it! Yeah, I think the score might have different weights for different people.  License and creation info are generally more valuable. I don't see much value in file digests either, even if a static file was changed, go module version would be changed.
